# Generated by Django 3.2.6 on 2021-11-07 04:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to=app.models.fa)),
            ],
        ),
        migrations.CreateModel(
            name='indextbanimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='index', max_length=15)),
                ('image', models.FileField(upload_to='static/dataset')),
            ],
        ),
        migrations.CreateModel(
            name='indextbplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='index', max_length=15)),
                ('image', models.FileField(upload_to='static/dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PlantTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to=app.models.fp)),
            ],
        ),
        migrations.CreateModel(
            name='sampletb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='image', max_length=15)),
                ('image', models.FileField(upload_to='static/media')),
            ],
        ),
    ]
