# Generated by Django 3.2.6 on 2021-10-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagetb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='index', max_length=15)),
                ('image', models.FileField(upload_to='static/dataset')),
            ],
        ),
        migrations.CreateModel(
            name='indextb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='index', max_length=15)),
                ('image', models.FileField(upload_to='static/dataset')),
            ],
        ),
    ]
