# Generated by Django 3.2.6 on 2021-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imagetb_indextb'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demo', max_length=15)),
                ('data', models.TextField()),
            ],
        ),
    ]
