# Generated by Django 3.2.6 on 2021-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_datamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetb',
            name='image',
            field=models.FileField(unique=True, upload_to='static/dataset'),
        ),
    ]
