# Generated by Django 3.2.6 on 2021-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_imagetb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetb',
            name='image',
            field=models.FileField(null=True, upload_to='static/dataset'),
        ),
    ]
